### ISSUE TITLE
Clang 10 compiler errors

### ISSUE THREAD

**Issue by kpine** [OpenZWave/open-zwave#2280]
While compiling with Clang 10 (master branch, 54bfecf26d50fac982bec86919e68646821be232), I encountered these errors, which look like actual bugs.

```
/src/ozw/cpp/src/command_classes/CentralScene.cpp:212:42: error: bitwise comparison always evaluates to false [-Werror,-Wtautological-bitwise-compare]
                                                        m_slowrefresh = (_data[2] & 0x80) == 1 ? true : false;
                                                                        ~~~~~~~~~~~~~~~~~~^~~~
/src/ozw/cpp/src/command_classes/Alarm.cpp:243:61: error: bitwise comparison always evaluates to false [-Werror,-Wtautological-bitwise-compare]
                                                bool NotificationSequencePresent = ((_data[7] & 0x80) == 1);
                                                                                    ~~~~~~~~~~~~~~~~~~^~~~
```

The error was introduced in https://github.com/OpenZWave/open-zwave/commit/406549b4224db9d527d2311577a8b961d4179623. I'm not sure what compiler was complaining (vc++?), but for clang 10 and gcc 8 on Linux the original code reports no errors. Perhaps that compiler would be happy with a `static_cast<bool>(_data[2] & 0x80)`?

**Comment by Fishwaldo** [comment]
Should be fixed.
