### ISSUE TITLE
r697 still doesn't compile on Ubuntu 13.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#247]
```
What steps will reproduce the problem?
1. Install Ubuntu
2. Install openzwave testing 2013-11-13
3. Try to make/compile

The error output is:
g++ -c -Wall -Wno-unknown-pragmas -Wno-inline -Wno-format -Werror -g -DDEBUG 
-DLOG_STDERR -fPIC -I ../../src -I ../../src/command_classes/ -I 
../../src/value_classes/ -I ../../src/platform/ -I ../../src/platform/unix -I 
../../tinyxml/ -I ../../hidapi/hidapi/ -o LogImpl.o 
../../src/platform/unix/LogImpl.cpp
../../src/platform/unix/LogImpl.cpp: In member function ‘std::string 
OpenZWave::LogImpl::GetThreadId()’:
../../src/platform/unix/LogImpl.cpp:291:73: error: format ‘%x’ expects 
argument of type ‘unsigned int’, but argument 4 has type ‘pthread_t {aka 
long unsigned int}’ [-Werror=format=]
  snprintf( buf, sizeof(buf), "%08x ", (long unsigned int)pthread_self() );
                                                                         ^
../../src/platform/unix/LogImpl.cpp:291:73: error: format ‘%x’ expects 
argument of type ‘unsigned int’, but argument 4 has type ‘pthread_t {aka 
long unsigned int}’ [-Werror=format=]
cc1plus: all warnings being treated as errors
make: *** [LogImpl.o] Error 1

Modifying the LogImpl.cpp and replace line:
snprintf( buf, sizeof(buf), "%08x ", (long unsigned int)pthread_self() );

to:
snprintf( buf, sizeof(buf), "%08x ", (unsigned int)pthread_self() );

Solves the problem.

Other option is to remove all "-Werror" from the Makefile, but that's a choice 
of the openzwave team can make.

What is the expected output? What do you see instead?
openzwave library compiles successfully on ubuntu 13.10

What version of the product are you using? On what operating system?
r697 - testing branch 2013-11-13

Please include the file OZW_Log.txt from your program. Make sure the file
zwcfg*.xml is NOT present.

Please provide any additional information below.

```

Original issue reported on code.google.com by `uAle...@gmail.com` on 28 Nov 2013 at 8:52
- Merged into: #238
